-- =============================================================================
-- AGENT COMMERCE - Load Data via COPY INTO
-- =============================================================================
-- Loads CSV data from @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE into all tables.
-- Run AFTER 02_create_tables.sql
-- =============================================================================

USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;

-- ===========================================================================
-- CART_OLTP schema
-- ===========================================================================

COPY INTO AGENT_COMMERCE.CART_OLTP.CART_SESSIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/cart_sessions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.CART_ITEMS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/cart_items.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.FULFILLMENT_OPTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/fulfillment_options.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.ORDERS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.ORDER_ITEMS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/order_items.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.PAYMENT_METHODS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/payment_methods.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CART_OLTP.PAYMENT_TRANSACTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/payment_transactions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- ===========================================================================
-- CUSTOMERS schema
-- ===========================================================================

COPY INTO AGENT_COMMERCE.CUSTOMERS.CUSTOMERS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CUSTOMERS.CUSTOMER_FACE_EMBEDDINGS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/customer_face_embeddings.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.CUSTOMERS.SKIN_ANALYSIS_HISTORY
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/skin_analysis_history.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- ===========================================================================
-- INVENTORY schema
-- ===========================================================================

COPY INTO AGENT_COMMERCE.INVENTORY.LOCATIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/locations.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.INVENTORY.STOCK_LEVELS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/stock_levels.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.INVENTORY.INVENTORY_TRANSACTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/inventory_transactions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- ===========================================================================
-- PRODUCTS schema
-- ===========================================================================

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCTS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCT_VARIANTS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_variants.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCT_MEDIA
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_media.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCT_LABELS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_labels.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCT_INGREDIENTS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_ingredients.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRODUCT_WARNINGS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_warnings.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PRICE_HISTORY
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/price_history.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.PRODUCTS.PROMOTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/promotions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- ===========================================================================
-- SOCIAL schema
-- ===========================================================================

COPY INTO AGENT_COMMERCE.SOCIAL.PRODUCT_REVIEWS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/product_reviews.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.SOCIAL.SOCIAL_MENTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/social_mentions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO AGENT_COMMERCE.SOCIAL.INFLUENCER_MENTIONS
FROM @AGENT_COMMERCE.UTIL.CSV_DATA_STAGE/influencer_mentions.csv
FILE_FORMAT = (FORMAT_NAME = 'AGENT_COMMERCE.UTIL.CSV_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Note: No CSV files found on stage for the following tables:
-- CUSTOMERS.FACE_IMAGE_PROCESSING (generated at runtime)
-- PRODUCTS.LABEL_EXTRACTIONS_STAGING (generated at runtime)
-- PRODUCTS.PRODUCT_INGREDIENTS_BACKUP (backup table)
-- PRODUCTS.PRODUCT_INGREDIENTS_URL_BACKUP (backup table)
-- PRODUCTS.PRODUCT_WARNINGS_BACKUP (backup table)
-- PRODUCTS.PRODUCT_WARNINGS_URL_BACKUP (backup table)
-- SOCIAL.TRENDING_PRODUCTS (computed table)
